pipeline {
    agent any

    environment {
        dockerhub=credentials('dockerhub')
    }

    stages {

        stage("verify tooling") {
            steps {
                sh '''
                    docker version
                    docker info
                    python3 --version
                    pip3 --version
                '''
            }
        }

        stage("Install requirements") {
            steps {
                dir("CloudContainer") {
                    sh '''
                        pip3 install -r requirements_test.txt
                    '''
                }
            }
        }

        stage("Run tests") {
            steps {
                dir("CloudContainer") {
                    sh "pytest --version"
                    sh "pytest"
                }
            }
        }
    }
}